name: 'Open Github Issue'
author: robhowells
description: 'Opens a Github issue'
inputs:
  token:
    description: 'Github token'
    required: true
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body'
  assignees:
    description: 'Issue assignees'
outputs:
  issue:
    description: 'The isue object as a JSON string'
runs:
  using: 'node12'
  main: 'dist/index.js'
